dist: xenial
sudo: false
language: java
jdk:
  - openjdk13

notifications:
  email: false

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

