dist: xenial
sudo: false
language: java
jdk:
  - openjdk13

git:
  depth: false

notifications:
  email: false

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle/'
    - '.gradle'

script:
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube
