dist: trusty
sudo: false
language: java
jdk:
  - openjdk11

notifications:
  email: false

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - sonar-scanner
